version: '3'
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '8081:8081'
    restart: unless-stopped
    depends_on:
      - db
    environment:
      env_file: ./backend/.env

  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    restart: unless-stopped

  db:
    image: postgres:14.11-alpine
    restart: unless-stopped
    volumes:
      - ./create_test_db.sql:/docker-entrypoint-initdb.d/create_test_db.sql
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      env_file: ./backend/.env
    healthcheck:
      test: "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"
      interval: "10s"
      timeout: "5s"
      retries: 5

volumes:
  postgres_data:
