name: Build and Deploy
on:
  push:
    branches:
      - gh-pages # assuming you want to deploy from the main branch
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true # typically should be true for deployments

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            .yarn
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install Dependencies
        uses: actions/setup-node@v4
        with:
          node-version: '14' # specify your node version
          cache: 'yarn'

      - name: Install and Build
        run: |
          yarn install
          yarn build # ensure this builds to the 'build' directory

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages # target branch to deploy to
          folder: build # folder to deploy
