name: Build and Deploy
on:
  push:
    branches:
      - gh-pages # assuming you want to deploy from the main branch
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true # typically should be true for deployments

      - name: Install Dependencies
        uses: actions/setup-node@v4

      - name: Install and Build
        run: |
          yarn install && yarn build

      - name: Deploy 🚀
        run: |
          git config --global user.name $user_name
          git config --global user.email $user_email
          git remote set-url origin https://${github_token}@github.com/${repository}
          npm run deploy
        env:
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          github_token: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}
          repository: ${{ github.repository }}
